# Generated by Django 2.2.3 on 2019-07-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('duracao', models.IntegerField()),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roteiro.Localizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_chegada', models.DateField()),
                ('data_de_saida', models.DateField()),
                ('numero_de_pessoas', models.IntegerField()),
                ('passeios', models.ManyToManyField(blank=True, to='roteiro.Passeio')),
            ],
        ),
    ]
