# Generated by Django 2.2.3 on 2019-08-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passeios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_chegada', models.DateField()),
                ('data_de_saida', models.DateField()),
                ('numero_de_pessoas', models.IntegerField()),
                ('passeios', models.ManyToManyField(blank=True, to='passeios.Passeio')),
            ],
        ),
    ]
